name: Release

on:
  push:
    tags:
      - 'v*' # Déclenche le workflow quand une balise (tag) commençant par "v" est poussée

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Install Dependencies
        run: pnpm install

      - name: Build Release Files
        run: pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release/
          retention-days: 5

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/** # Télécharge tous les fichiers du dossier "release"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
